#pragma once

#include "zadania-arytmetyka-wskaznikow/ZadArytmetykaWskaznikowPrzesuniecie.hpp"
#include "zadania-funkcja-main/ZadEnumExample.hpp"
#include "zadania-funkcja-main/ZadClassExample.hpp"
#include "zadania-funkcja-main/ZadCharExample.hpp"

#include "zadania-w-trakcie-zajec/ZadStringExample.hpp"

//#include "zadania-zwracanie-przez-funkcje/ZadPrzekazywanie.hpp"
#include "zadania-zwracanie-przez-funkcje/ZadZwracanie.hpp"
#include "zadania-zwracanie-przez-funkcje/ZadPrzeciazaniePole.hpp"
#include "zadania-zwracanie-przez-funkcje/ZadPrzeciazanieDodaj.hpp"
#include "zadania-zwracanie-przez-funkcje/ZadPrzeciazaniePlus.hpp"
#include "zadania-zwracanie-przez-funkcje/LPrzeciazaniePotega.hpp"

#include "zadania-arytmetyka-wskaznikow/ZadArytmetykaWskaznikowZamiana.hpp"
#include "zadania-arytmetyka-wskaznikow/ZadArytmetykaWskaznikowSuma.hpp"
#include "zadania-arytmetyka-wskaznikow/ZadArytmetykaWskaznikowZnajdowanie.hpp"
#include "zadania-arytmetyka-wskaznikow/ZadArytmetykaWskaznikowRoznica.hpp"
#include "zadania-arytmetyka-wskaznikow/ZadArytmetykaWskaznikowKopiowanie.hpp"
#include "zadania-arytmetyka-wskaznikow/ZadAdresowaniePamieci.hpp"
#include "zadania-arytmetyka-wskaznikow/ZadArytmetykaWskaznikowTabliceA.hpp"
//#include "zadania-arytmetyka-wskaznikow/ZadArytmetykaWskaznikowTabliceB.hpp"
#include "zadania-arytmetyka-wskaznikow/ZadArytmetykaWskaznikowTablica2D.hpp"
#include "zadania-arytmetyka-wskaznikow/ZadArytmetykaWskaznikow.hpp"
#include "zadania-arytmetyka-wskaznikow/ZadOperatoryPzypisania.hpp"
#include "zadania-arytmetyka-wskaznikow/LBitoweOperatoryLogiczneSingleVariable.hpp"

#include "zadania-operacje-wejscia-wyjscia/LStringStream.hpp"
#include "zadania-operacje-wejscia-wyjscia/LManipulacjaStrumieniemCout.hpp"
#include "zadania-operacje-wejscia-wyjscia/ZadCinCoutFile.hpp"
//#include "zadania-operacje-wejscia-wyjscia/ZadCandCPP.hpp"
#include "zadania-operacje-wejscia-wyjscia/ZadTabelaFormat.hpp"
#include "zadania-operacje-wejscia-wyjscia/ZadTemperaturaFormat.hpp"
#include "zadania-operacje-wejscia-wyjscia/ZadDaneNaukoweFormat.hpp"
#include "zadania-operacje-wejscia-wyjscia/ZadParzysta.hpp"
//#include "zadania-operacje-wejscia-wyjscia/ZadParzystaCase.hpp"
#include "zadania-operacje-wejscia-wyjscia/ZadPetle.hpp"
//#include "zadania-operacje-wejscia-wyjscia/ZadSwitch.hpp"
#include "zadania-operacje-wejscia-wyjscia/ZadForA.hpp"
#include "zadania-operacje-wejscia-wyjscia/LSilnia.hpp"
#include "zadania-operacje-wejscia-wyjscia/LKsztalt.hpp"
// #include "zadania-operacje-wejscia-wyjscia/LWhileA.hpp"
// #include "zadania-operacje-wejscia-wyjscia/LGra.hpp"
#include "zadania-operacje-wejscia-wyjscia/ZadStudent.hpp"
#include "zadania-operacje-wejscia-wyjscia/ZadPreprocesor.hpp"

#include "zadania-klasy/ZadClass.hpp"
#include "zadania-klasy/ZadStruct.hpp"
#include "zadania-klasy/ZadUnia.hpp"
#include "zadania-klasy/ZadKlasaKonstruktor.hpp"
#include "zadania-klasy/ZadStructKonstruktor.hpp"
#include "zadania-klasy/ZadPrzyjazn.hpp"
#include "zadania-klasy/ZadMetodyAbstrakcyjne.hpp"

#include <string>