//
// Created by Jakub on 15.05.2026.
//

#ifndef SOLUTIONS_ZADARYTMETYKAWSKAZNIKOWPRZESUNIECIE_HPP
#define SOLUTIONS_ZADARYTMETYKAWSKAZNIKOWPRZESUNIECIE_HPP

#endif //SOLUTIONS_ZADARYTMETYKAWSKAZNIKOWPRZESUNIECIE_HPP