//
// Created by Jakub on 15.05.2026.
//

#ifndef SOLUTIONS_ZADARYTMETYKAWSKAZNIKOWZAMIANA_HPP
#define SOLUTIONS_ZADARYTMETYKAWSKAZNIKOWZAMIANA_HPP

#endif //SOLUTIONS_ZADARYTMETYKAWSKAZNIKOWZAMIANA_HPP