//
// Created by student on 27.03.2026.
//

#ifndef CPPCOURSEEXCERCISES_EXCERCISESCONTAINER_HPP
#define CPPCOURSEEXCERCISES_EXCERCISESCONTAINER_HPP


class ExcercisesContainer {
};


#endif //CPPCOURSEEXCERCISES_EXCERCISESCONTAINER_HPP