#include "includes.hpp"
#include <string>
#include <iostream>

const auto main_separator = std::string(100, '=');
const auto separator = std::string(100, '-');

int main() {
    std::cout << "\n" << main_separator << "\n" << std::endl;
    runZadEnumExample();
    std::cout << "\n" << separator << "\n" << std::endl;
    runZadClassExample();
    std::cout << "\n" << separator << std::endl;
    runStringFunctionsExample();
    std::cout << "\n" << separator << std::endl;
    runZadCharExample();
    std::cout << "\n" << separator << std::endl;
    runZadZwracanie();
    std::cout << "\n" << separator << std::endl;
    runZadPrzeciazeniePole();
    std::cout << "\n" << separator << std::endl;
    runZadPrzeciazenieDodaj();
    std::cout << "\n" << separator << std::endl;
    runZadPrzeciazaniePlus();
    std::cout << "\n" << separator << std::endl;
    runLPrzeciazaniePotega();
    std::cout << "\n" << separator << std::endl;
    runZadArytmetykaWskaznokowZamiana();
    std::cout << "\n" << separator << std::endl;
    runZadArytmetykaWskaznikowSuma();
    std::cout << "\n" << separator << std::endl;
    runZadArytmetykaWskaznikowZnajdowanie();
    std::cout << "\n" << separator << std::endl;
    runZadArytmetykaWskaznikowPrzesuniecie();
    std::cout << "\n" << separator << std::endl;
    runZadArytmetykaWskaznikowRoznica();
    std::cout << "\n" << separator << std::endl;
    runZadArytmetykaWskaznikowKopiowanie();
    std::cout << "\n" << separator << std::endl;
    runZadAdresowaniePamieci();
    std::cout << "\n" << separator << std::endl;
    runZadArytmetykaWskaznikowTabliceA();
    std::cout << "\n" << separator << std::endl;
    std::cout << "*runZadArytmetykaWskaznikowTabliceB() here*";
    //runZadArytmetykaWskaznikowTabliceB();
    std::cout << "\n" << separator << std::endl;
    runZadArytmetykaWskaznikowTablica2D();
    std::cout << "\n" << separator << std::endl;
    runZadArytmetykaWskaznikow();
    std::cout << "\n" << separator << std::endl;
    runZadOperatoryPzypisania();
    std::cout << "\n" << separator << std::endl;
    runLBitoweOperatoryLogiczneSingleVariable();
    std::cout << "\n" << separator << std::endl;
    runLStringStream();
    std::cout << "\n" << separator << std::endl;
    runLManipulacjaStrumieniemCout();
    std::cout << "\n" << separator << std::endl;
    runZadCinCoutFile();
    std::cout << "\n" << separator << std::endl;
    std::cout << "*runZadCandCPP() here*";
    //runZadCandCPP();
    std::cout << "\n" << separator << std::endl;
    runZadTabelaFormat();
    std::cout << "\n" << separator << std::endl;
    runZadTemperaturaFormat();
    std::cout << "\n" << separator << std::endl;
    runZadDaneNaukoweFormat();
    std::cout << "\n" << separator << std::endl;
    runZadParzysta();
    std::cout << "\n" << separator << std::endl;
    //runZadParzystaCase();
    std::cout << "*runZadParzystaCase() here*";
    std::cout << "\n" << separator << std::endl;
    runZadPetle();
    std::cout << "\n" << separator << std::endl;
    //runZadSwitch();
    std::cout << "*runZadSwtich() here*";
    std::cout << "\n" << separator << std::endl;
    runZadForA();
    std::cout << "\n" << separator << std::endl;
    runZadSilnia();
    std::cout << "\n" << separator << std::endl;
    runZadKsztalt();
    std::cout << "\n" << separator << std::endl;
    std::cout << "*runZadWhileA() here*";
    //runZadWhileA();
    std::cout << "\n" << separator << std::endl;
    std::cout << "*runLGra() here*";
    //runZadGra();
    std::cout << "\n" << separator << std::endl;
    runZadStudent();
    std::cout << "\n" << separator << std::endl;
    runZadPreprocesor();
    std::cout << "\n" << separator << std::endl;
    runZadClass();
    std::cout << "\n" << separator << std::endl;
    runZadStruct();
    std::cout << "\n" << separator << std::endl;
    runZadUnia();
    std::cout << "\n" << separator << std::endl;
    runZadKlasaKonstruktor();
    std::cout << "\n" << separator << std::endl;
    runZadStructKonstruktor();
    std::cout << "\n" << separator << std::endl;
    runZadPrzyjazn();
    std::cout << "\n" << separator << std::endl;
    runZadMetodyAbstrakcyjne();
    std::cout << "\n" << main_separator << "\n" << std::endl;
    return 0;
}